spring:
  mvc:
    view:
      suffix: /
      prefix: .jsp

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cmfz
    username: root
    password: root
  profiles:
    active: manager  # 激活那个配置文件
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss #全局日期格式转换
    time-zone: GMT+08   #设置时区 为+8时
  http:
    multipart:
      max-file-size: 10MB  #  设置上传问件的大小
      max-request-size: 10MB  #这是设置上传文件的 总 大小   多个上传

mybatis:
  mapper-locations: classpath:com/baizhi/cmfz/mapper/*.xml
  type-aliases-package: com.baizhi.cmfz.entity # 给实体类起别名
server:
  jsp-servlet:
    init-parameters:
      development: true  # 开启jsp的热部署
# ===================================================================
# 分布式文件系统FDFS配置
# ===================================================================
  #fdfs:
  # so-timeout: 1501
  # connect-timeout: 601
    # thumb-image: #缩略图生成参数
    # width: 150
    # height: 150
  #tracker-list: #TrackerList参数,支持多个
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:
    width: 150
    height: 150
  tracker-list:
    - 192.168.136.132:22122